### ISSUE TITLE
Add clean to package.json

### ISSUE THREAD

**Issue by Uhuh** [siggame/colisee-matchmaker#10]

**Comment by russleyshaw** [comment]
Please use the `rimraf` module.
`npm install --save-dev rimraf`

Only worry about .js files that are built in source for now. 

The result will be something to this effect.
```
    "clean:src": "rimraf src/**/*.js src/*.js",
    "clean:test": "rimraf test/**/*.js test/*.js",
    "clean:misc": "rimraf dist/ node_modules/",
```

**Comment by russleyshaw** [comment]
also a `clean: npm run clean:src && npm run clean:test && npm run clean:misc`
